### ISSUE TITLE
Voltage range for 74CBTLV3257

### ISSUE THREAD

**Issue by gnaghi** [MouseBiteLabs/Super-Nintendo-Cartridges#1]
The datasheet of the 74CBTLV3257 defines the working voltage range from 2.3 V to 3.6 V. 
But the SNES outputs +5V to the cartridge bus.
Would level shifter be useful ?

**Comment by MouseBiteLabs** [comment]
I specify the 5V tolerant parts in the BOM, where do you see the LV version?

https://www.mouser.com/ProductDetail/595-SN74CBT3257CPWR

Also I forgot I uploaded files last week - I've found an issue and I need to rev the board, so if you downloaded the files that were there up until just now, I would recommend waiting until the new ones are uploaded :)

**Comment by gnaghi** [comment]
The parts used on the schematic are all the LV version.

![image](https://github.com/user-attachments/assets/fdaed8b2-e6ac-47ce-9745-61800e13a2d5)

Thanks for the warning about waiting :).

**Comment by MouseBiteLabs** [comment]
I have a bad habit of picking symbols without looking at the exact part numbers, and saving that part for when I'm putting together the BOM. Usually people don't check the schematic for the part numbers. But I guess I should be consistent - I'll fix this for when I upload the new version. Thanks!
